"""empty message

Revision ID: 2a56a166d1da
Revises: c454c87d5715
Create Date: 2025-02-18 20:07:10.964495

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2a56a166d1da"
down_revision: Union[str, None] = "c454c87d5715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
