"""empty message

Revision ID: c454c87d5715
Revises: 8174285e7286
Create Date: 2025-02-18 20:06:12.099142

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c454c87d5715"
down_revision: Union[str, None] = "8174285e7286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
