name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        DB_HOST: postgres
        DB_PORT: 5432
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Tests Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$HOME/.poetry/bin:$PATH"
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run Tests
      run: |
        export PATH="$HOME/.local/bin:$HOME/.poetry/bin:$PATH"
        poetry install
        poetry run pip install 'asyncpg==0.29.0'
        cd src && poetry run python -m pytest -v -s
